#!/bin/bash

TMI=tmi/tmi

mkdir -p tmi/out

echo "predicting disparities..."

#python3 tmi.py || exit 1

echo "done"

echo "converting disparities..."

mkdir -p tmi/results/Stereo_SD_d_complete


for i in $(seq 1 42); do
	disp=tmi/out/${i}.disp
	calib=/org/share/MediData/MedData/TMI\ Dataset/Stereo_SD_d_complete/Stereo_SD_d_complete_${i}/Stereo_SD_d_complete_${i}_Calibration.txt
	#calib=/org/share/MediData/MedData/TMI\ Dataset/Stereo_SD_d_all/Stereo_SD_d_all_${i}/Stereo_SD_d_all_${i}_Calibration.txt
	out=tmi/results/Stereo_SD_d_complete/Stereo_SD_d_complete_${i}_result.xyz

	mkdir -p tmi/results/Stereo_SD_d_complete

	echo $TMI $disp $calib
	$TMI "$disp" "$calib" || exit 1

	echo cp 3dPoints.xyz "$out"
	mv 3dPoints.xyz "$out" || exit 1
done

echo "done"
